export type FETCH_GALLERY = 'FETCH_GALLERY';
export const FETCH_GALLERY: FETCH_GALLERY = 'FETCH_GALLERY';

export type SET_GALLERY = 'SET_GALLERY';
export const SET_GALLERY: SET_GALLERY = 'SET_GALLERY';

export type SELECT_IMAGE = 'SELECT_IMAGE';
export const SELECT_IMAGE: SELECT_IMAGE = 'SELECT_IMAGE';

export type SET_PAGE = 'SET_PAGE';
export const SET_PAGE: SET_PAGE = 'SET_PAGE';

export type SET_LAST_LOADED_PAGE = 'SET_LAST_LOADED_PAGE';
export const SET_LAST_LOADED_PAGE: SET_LAST_LOADED_PAGE = 'SET_LAST_LOADED_PAGE';
