export type SET_ORIGINAL_IMAGE = 'SET_ORIGINAL_IMAGE';
export const SET_ORIGINAL_IMAGE: SET_ORIGINAL_IMAGE = 'SET_ORIGINAL_IMAGE';

export type SET_MOSAIC = 'SET_MOSAIC';
export const SET_MOSAIC: SET_MOSAIC = 'SET_MOSAIC';

export type GENERATE_MOSAIC = 'GENERATE_MOSAIC';
export const GENERATE_MOSAIC: GENERATE_MOSAIC = 'GENERATE_MOSAIC';
