export type SET_ORIGINAL_IMAGE = 'SET_ORIGINAL_IMAGE';
export const SET_ORIGINAL_IMAGE: SET_ORIGINAL_IMAGE = 'SET_ORIGINAL_IMAGE';

export type SET_MOSAIC = 'SET_MOSAIC';
export const SET_MOSAIC: SET_MOSAIC = 'SET_MOSAIC';

export type GENERATE_MOSAIC = 'GENERATE_MOSAIC';
export const GENERATE_MOSAIC: GENERATE_MOSAIC = 'GENERATE_MOSAIC';

export type SHARE_IMAGE = 'SHARE_IMAGE';
export const SHARE_IMAGE: SHARE_IMAGE = 'SHARE_IMAGE';

export type SET_SHARED_IMAGE = 'SET_SHARED_IMAGE';
export const SET_SHARED_IMAGE: SET_SHARED_IMAGE = 'SET_SHARED_IMAGE';
